### ISSUE TITLE
Thanks to this repo and my custom changes

### ISSUE THREAD

**Issue by Himujjal** [siduck76/chad-nvim#12]
Thanks to this repo for making a base for me to setup neovim. I did make a few custom changes.
I would be ready to discuss on that front and what additions seem useful to you.
I will make a PR after the discussion.

I was always looking for a neovim config which I can say to neovim beginners like "oh! here is a link. use this config and you are good to go". I think this one fits perfectly.

BTW, here are a few changes I did:

### Plugins:

1. Added `kommentary` plugin for comments (modified a few things to make everything single comments based)
2. `nvim-toggleterm` for terminal toggles
3. `markdown-preview` for markdown

### LSP & Tree-sitter 

2. Zig 
3. Nim
4. Rust
5. Java
6. C/CPP
7. Ocaml
8. Go

### Mappings

1. Added navigation among buffers using `<leader>j` & `<leader>k`. Close buffer using `<C-w>`
2. Some extra LSP mappings (very minimal)
3. Resizing windows
4. `<leader>/` for searching using telescope and `ripgrep`

Btw, here is the latest change https://github.com/Himujjal/dotfiles

**Comment by siduck76** [comment]
Thanks for the appreciation , I'm glad you liked my config . For the lsp/treesitter part I think it would be better to include it in the install script and print the list of languages (  supported in our config ) and prompt the user to select and install only lsp servers he wants . Also adding Kommentary and markdown preview support would be great!

**Comment by Himujjal** [comment]
LSP & Tree-sitter is of course my preference.

Other than that. I did add a few mappings for easier navigation across buffers & splits.

**Comment by marvelman3284** [comment]
I'm actually working on a feature that allows you to select which lsp you want when installing.

**Comment by jaydamani** [comment]
these may come handy if you are implementing that : [nvim-lspupdate](https://github.com/alexaandru/nvim-lspupdate) and [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall)

**Comment by siduck76** [comment]
nvim-lspinstall supports only some languages

**Comment by Himujjal** [comment]
__Here's my opinion, if you guys are at all willing to go forward.__

Language Server Protocol and Tree-sitter highlighting goes hand in hand. Its all that is needed to make sure that a language is usable from the user's perspective.
There should be something like `nvim-lspconfig`, `nvim-lspinstall` & `nvim-treesitter` to make it one plugin that installs language features all at once.

Preferably I would say, simply do: `:LangInstall zig` which installs `tree-sitter-zig` and `zls` both at the same time. This will save a lot of time and effort I guess. What else do you think are required for a particular language to work?

---

> nvim-lspinstall supports only some languages
@siduck76. I think with time, this willl include all languages. I will make the PR for Svelte and Zig for now. I think you guys should too if you feel your language doesn't have the config.

**Comment by Himujjal** [comment]
Regarding this PR, I will request you to go through https://github.com/Himujjal/dotfiles where I will certainly strip down and refactor to make this PR possible. But the basic idea behind this issue is in that repo.

**Comment by siduck76** [comment]
@Himujjal That would be great!!, But I'm totally unaware of making vim plugins and my lua knowledge is very basic too . If you'd make a plugin for it then we'll include it it , if not then we can include the lsp servers installation in the install.sh script itself or we could wait for lspinstall to support more languages :)

**Comment by Himujjal** [comment]
I could make the plugin for sure!

Anyways. do have a look at the dotfiles link I gave you. If possible try it out. I will make a PR based on that.

**Comment by siduck76** [comment]
yeah I already did , I would accept kommentary , markdown preview and toggleterm features for now and we'll keep the lsp stuffs on hold for a while. Some new stuffs have been added recently , so keep your repo up to-date .

**Comment by siduck76** [comment]
I'll close this issue for now , feel free to reopen it when you're ready with the PR :)
