### ISSUE TITLE
Syntax on/enable not necessary

### ISSUE THREAD

**Issue by mjlbach** [siduck76/chad-nvim#37]
Are these lines necessary:
https://github.com/siduck76/chad-nvim/blob/49c1f84e6e1cf0b026d1e0b2b910a40c19b56b76/init.lua#L24-L25

per `:help nvim-defaults`

```
  2. Defaults                                                 nvim-defaults

  - Syntax highlighting is enabled by default
  - ":filetype plugin indent on" is enabled by default
```

These lines will reset filetype plugin rules which clear autocommands/language server autocommands necessary for attaching the buffer

**Comment by siduck76** [comment]
@mjlbach I think those are still required , check the difference : 
 
 without those
 
![image](https://user-images.githubusercontent.com/59060246/117169719-f9cd5980-ade6-11eb-8c20-a9c39ebc7a73.png)

with them

![image](https://user-images.githubusercontent.com/59060246/117169753-02259480-ade7-11eb-99d8-76ef87d2af10.png)

And yes , only one of these : syntax on or syntax enable is needed! I'll just put syntax enable for now

**Comment by mjlbach** [comment]
Hmm, we should be doing 'syntax enable` by default now https://github.com/neovim/neovim/commit/b0a1d1eb64e84eb9f25c48204ba4a36735cf1e75

I don't actually use chad-nvim, so I can't test, but we had a user asking questions on matrix about why lspconfig wasn't autostarting which was related to the use of the syntax command

**Comment by siduck76** [comment]
yea but neovim doesnt follow syntax highlighting from the colorscheme if I dont see 'system enable' . It uses some different colors :/.

**Comment by siduck76** [comment]
I got to know that treesitter turns syntax off , by using syntax none so I think thats the cause why my neovim requires 'syntax enable' . I think this should be clear. @mjlbach

**Comment by mjlbach** [comment]
Where do you see that? I only see: https://github.com/nvim-treesitter/nvim-treesitter/blob/4a802282207cea3bc54c5e182c063739cdcda736/lua/nvim-treesitter/highlight.lua#L114-L118

**Comment by siduck76** [comment]
I think I read it here https://github.com/nvim-treesitter/nvim-treesitter/issues/359#issuecomment-683386760

**Comment by mjlbach** [comment]
I don't see where it is in the code, anyways I'm not sure it particularly matters as it does it per buffer triggered by filetype (so it shouldn't affect your other buffers). Anyways, closing this. If anyone has issues with `lspconfig` not triggering any call involving `syntax` is a good place to start looking :)

**Comment by siduck76** [comment]
@mjlbach I found the code , the syntax is set to none ( " ") https://github.com/neovim/neovim/blob/27da5511a0c0b12fcabe29cf38c3f8a0f0b444b9/runtime/lua/vim/treesitter/highlighter.lua#L160 . Also my friend says that we dont need both 'syntax on' or 'syntax enable' . without those I get weird colors on syntax highlighting . I think thats because my colorscheme isnt treesitter supported :l .
