### ISSUE TITLE
Can't close side bar

### ISSUE THREAD

**Issue by marvelman3284** [siduck76/chad-nvim#38]
After pulling the most recent commit I am now getting an error where I am not able to close the side bar. The error looks like this:
![image](https://user-images.githubusercontent.com/58921302/117323878-481d3f80-ae5d-11eb-808a-0f56845f5fa3.png)

Thanks in advance!

**Comment by siduck76** [comment]
What does :NvimTreeToggle do?

**Comment by marvelman3284** [comment]
It returns the same error

**Comment by siduck76** [comment]
compile neovim-nightly from source and check again @marvelman3284

**Comment by marvelman3284** [comment]
@siduck76 still getting the same error.

**Comment by siduck76** [comment]
@marvelman3284 try :PackerUpdate

**Comment by siduck76** [comment]
@marvelman3284 try :PackerUpdate

**Comment by marvelman3284** [comment]
@siduck76  still receiving the error

**Comment by siduck76** [comment]
> @siduck76  still receiving the error

Show me your neovim version

**Comment by marvelman3284** [comment]
![image](https://user-images.githubusercontent.com/58921302/117470257-9a756380-af24-11eb-8f4c-4d86d5bcf298.png)
@siduck76 here you go

**Comment by siduck76** [comment]
try compiling it from source .

**Comment by marvelman3284** [comment]
that fixed it. not sure why the aur version doesnt work

**Comment by siduck76** [comment]
@marvelman3284 I think because neovim nightly releases are not released regularly , the neovim-nightly-bin just uses those releases . As neovim's source code gets updated daily , compiling it would be the better since.
